import type { Site } from "@/types";
export const siteConfig: Site = {
  name: "webui.gopx",
  title: "GOPX WEBUI| webui.dev | 🚀 Building something people want!",
  description:
    "A comprehensive collection of meticulously crafted React components styled with Tailwind CSS and Framer Motion.",
  keywords: [
    "Gopal Verma",
    "www.gopx.dev",
    "webui.gopx.dev",
    "GOPX WEBUI",
    "gopx webui",
    "web ui component",
    "component library",
    "gopx.dev",
    "bettercallgopal",
    "gopalverma",
    "@bettercallgopal",
    "gopalverma1303",
    "github.com/GopalVerma1303",
    "programmer",
    "developer",
    "engineer",
    "founder",
    "indie",
    "designer",
    "x.com/bettercallgopal",
    "computer science",
    "web developer",
    "app developer",
    "blockchain developer",
    "full-stack developer",
    "software engineer",
    "Indian developer",
    "freelance developer",
    "open source",
    "open source contributor",
    "JavaScript developer",
    "TypeScript expert",
    "React developer",
    "Node.js developer",
    "mobile app development",
    "web application development",
    "UI/UX designer",
    "tech entrepreneur",
    "startup founder",
    "coding",
    "programming",
    "software development",
    "tech innovator",
    "digital solutions",
    "custom software development",
    "API development",
    "database design",
    "cloud computing",
    "DevOps",
    "agile methodologies",
    "frontend development",
    "backend development",
    "responsive web design",
    "cross-platform development",
    "code optimization",
    "performance tuning",
    "tech consulting",
    "Indian tech talent",
    "blogs",
    "projects",
    "showcase",
    "showcases",
    "portfolio",
    "devsite",
    "me",
    "gopal verma me",
    "notebooks",
    "web dev notes",
    "mlai notes",
    "web3 notes",
    "blockchain notes",
    "mobile dev notes",
    "app dev notes",
    "resources",
    "web dev",
    "webdev",
    "web development",
    "app dev",
    "appdev",
    "app development",
    "application development",
    "web3 dev",
    "web3 development",
    "blockchain dev",
    "blockchain development",
    "machine learning and artificial intelligence",
    "ml ai",
    "machine learning",
    "artificial intelligence",
    "ml",
    "ai",
    "machine learning engineer",
    "ai engineer",
    "artificial intelligence engineer",
    "miscellaneous resources",
    "miscellaneous links",
    "miscellaneous bank",
    "link bank",
    "curated links",
    "resources links",
  ],
  siteUrl: "https://webui.gopx.dev",
  creator: {
    name: "Gopal Verma",
    url: "https://gopx.dev/me",
  },
  ogImage: "https://bettercallgopal.vercel.app/og.jpeg",
  links: {
    x: "https://x.com/bettercallgopal",
    github: "https://github.com/GopalVerma1303",
  },
};
